[tool.poetry]
name = "surplus"
version = "2.0.0"
description = "Plus Code to iOS-Shortcuts-like shareable text"
authors = ["Mark Joshwel <mark@joshwel.co>"]
license = "Unlicence"
readme = "README.md"
include = ["surplus.py"]

[tool.poetry.dependencies]
python = "^3.11"
pluscodes = "^2022.1.3"
geopy = "^2.3.0"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.7.0"}
mypy = "^1.5.1"
isort = "^5.12.0"

[tool.poetry.scripts]
surplus = 'surplus:cli'
"s+" = 'surplus:cli'

[tool.black]
line-length = 90

[tool.isort]
line_length = 90
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
