#!/bin/sh
set -e

# get packages
yes | pkg upgrade
yes | pkg install python cronie termux-api termux-services wget

# install surplus
pip install https://github.com/markjoshwel/surplus/releases/latest/download/surplus-latest-py3-none-any.whl

# install whatsmeow
wget https://github.com/markjoshwel/whatsmeow-termux/releases/latest/download/mdtest.tar.gz
tar -xvf mdtest.tar.gz
chmod +x mdtest
mkdir -p ~/.local/bin/
mv mdtest ~/.local/bin/
rm mdtest.tar.gz

# install s+ow
mkdir -p ~/.local/bin/
curl https://raw.githubusercontent.com/markjoshwel/surplus/s+ow/s+ow > ~/.local/bin/s+ow
chmod +x ~/.local/bin/s+ow

# setup path
echo "export PATH=\$PATH:\$HOME/.local/bin/" >> ~/.profile

printf "\ns+ow setup complete\n"
