name: "continuous deployment: WhatsApp Bridge"

on:
  workflow_dispatch:
  push:
    paths:
      - "src/spow-whatsapp-bridge/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: |
          cd src/spow-whatsapp-bridge
          nix build .#termux

      - uses: actions/upload-artifact@v4
        with:
          name: "spow-whatsapp-bridge-android"
          path: src/spow-whatsapp-bridge/result
          retention-days: 14
