name: "continuous integration: s+ow"

on:
  workflow_dispatch:
  push:
    paths:
      - "src/surplus-on-wheels/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: |
          cd src/spow-whatsapp-bridge
          nix develop --command sh check.sh
