name: continuous integration

on:
  workflow_dispatch:
  push:
    paths:
      - "*.py"
      - "**.py"
      - "*.lock"
      - "pyproject.toml"

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.2
        with:
          ref: ${{ github.ref }}

      - name: install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
 
      - name: run checks
        run: devbox run hatch run check
