name: continuous integration

on:
  workflow_dispatch:
  push:
    paths:
      - "*.py"
      - "**.py"
      - "*.lock"
      - "pyproject.toml"

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install devbox  
        uses: jetpack-io/devbox-install-action@v0.7.0

      - name: build wheel
        id: build
        run: devbox run hatch build
        
      - name: run checks
        run: hatch show check
